spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: Team250T1478
    url: jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.mx-queretaro-1.oraclecloud.com))(connect_data=(service_name=gac52f4256f44f9_oraclebotp8hws_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
    username: TODOUSER
  jpa:
    database: ORACLE
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    user:
      name: Team25
      password: Team250T1478
Oracle:
  wallet-location: OracleJavaBot25\MtdrSpring\wallet

